### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by itsagoodbrain** [Mekhak/motion_deblur_dl#2]
Can you give some information on the versions needed to run the code? When I try I keep getting an issue importing the included pretrained model. So I'm assuming pytorch has changed something since this code was working.

**Comment by Mekhak** [comment]
I believe the new PyTorch releases are backward compatible with the previous versions, at least model loading-related stuff. However, you can try with v1.8.1.

**Comment by itsagoodbrain** [comment]
I get 
```
RuntimeError: Error(s) in loading state_dict for ResnetEncDec:
        Missing key(s) in state_dict: "bkbone.conv1.weight", "bkbone.bn1.weight", "bkbone.bn1.bias", "bkbone.bn1.running_mean", ............
        Unexpected key(s) in state_dict: "conv1.weight", "bn1.running_mean", "bn1.running_var", "bn1.weight", "bn1.bias", "layer1.0.conv1.weight", .............
```
I truncated the output because it seems it's every key. 

I could be doing something wrong on inputs, is this portion correct? `python predict.py -m pretrained/resnet50-19c8e357.pth`

**Comment by Mekhak** [comment]
Not, if you want to test inference then use one of the checkpoints:

For example:
`python predict.py -m checkpoints_old/CP_epoch5.pth`

**Comment by itsagoodbrain** [comment]
Thanks, I actually still got the same kind of error, enough googling later and I found that adding the keyword arg `strict=False` to `load_state_dict` was required to get it to load for me. Now just to see if it works.

**Comment by itsagoodbrain** [comment]
While that got it to run. The output was just grey, meaning I don't think I loaded it properly. Sorry and thanks for your quick replies.
